# Site settings
title: RiRi's blog of codes
email: richardweiss@richardweiss.org
description: > # this means to ignore newlines until "baseurl:"
   A blog about my experiments in programming & machine learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.richardweiss.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ririw

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
